apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamavailability-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: teamavail.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teamavail
            port:

              number: 80
